---
kind: Service
apiVersion: v1
metadata:
  name: fluxcloud
spec:
  selector:
    name: fluxcloud
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3032
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluxcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: fluxcloud
    spec:
      containers:
      - name: fluxcloud
        image: justinbarrick/fluxcloud:v0.3.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3032
        env:
        # Set these environment variables:
        - name: SLACK_OAUTH_TOKEN
          value: "some_token"
        - name: SLACK_DEFAULT_CHANNEL_ID
          value: "CGUTBEZPZ" # everyone
        - name: GITHUB_URL
          value: "https://github.com/justinbarrick/fluxcloud/"
        - name: LISTEN_ADDRESS
          value: ":3032"
